## Numpy

Импортировать NumPy под именем np

In [1]:
import numpy as np

Создать вектор (одномерный массив) размера 10, заполненный нулями

In [2]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

Создать вектор размера 10, заполненный единицами

In [45]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

Создать вектор размера 10, заполненный числом 2.5

In [44]:
np.full(10, 2.5)

array([2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5])

Создать вектор размера 10, заполненный нулями, но пятый элемент равен 1

In [43]:
ar = np.zeros(10)
ar.put(5, 1)
ar

array([0., 0., 0., 0., 0., 1., 0., 0., 0., 0.])

Развернуть вектор (первый становится последним)

In [42]:
np.flip(ar)

array([[0.59404323, 0.99264749],
       [0.59123688, 0.03312573],
       [0.34829448, 0.72826323],
       [0.92747753, 0.87753237],
       [0.80569669, 0.53410877],
       [0.91401382, 0.76617851],
       [0.32402891, 0.88170024],
       [0.16363132, 0.25581836],
       [0.34170311, 0.397537  ],
       [0.21029658, 0.6159334 ]])

Создать матрицу (двумерный массив) 3x3 со значениями от 0 до 8

In [41]:
table = np.arange(9).reshape(3, 3)
table

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

Найти индексы ненулевых элементов в [1,2,0,0,4,0]

In [40]:
test_array = np.array([1,2,0,0,4,0])
np.where(test_array != 0)[0]

array([0, 1, 4])

Создать 3x3 единичную матрицу

In [39]:
ones = np.ones([3, 3])
ones

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

Создать массив 3x3x3 со случайными значениями

In [38]:
random_array = np.random.rand(3, 3, 3)
random_array

array([[[0.67655514, 0.59622998, 0.47399939],
        [0.46822453, 0.29917652, 0.28863715],
        [0.38926314, 0.21239088, 0.42322517]],

       [[0.29104195, 0.81473485, 0.42258506],
        [0.01367719, 0.98614692, 0.314754  ],
        [0.27055911, 0.10384489, 0.74235943]],

       [[0.43469073, 0.66827687, 0.53921186],
        [0.79875573, 0.75221953, 0.41389857],
        [0.21654056, 0.42450874, 0.8939852 ]]])

Создать случайный вектор размера 30 и найти среднее значение всех элементов

In [37]:
random_vector = np.random.rand(30)
random_vector.mean()

0.6006973009886795

Перемножить матрицы 5x3 и 3x2

In [36]:
matrix1 = np.random.rand(5, 3)
matrix2 = np.random.rand(3, 2)
np.matmul(matrix1, matrix2)

array([[0.69552043, 0.2889209 ],
       [0.92415356, 0.172768  ],
       [0.7797005 , 0.0924583 ],
       [1.52742567, 0.17949509],
       [0.31142996, 0.07430366]])

Создать вектор размера 10 со значениями от 0 до 1, не включая ни то, ни другое

In [35]:
random_vector = np.random.rand(10)

Заменить максимальный элемент на ноль

In [34]:
random_vector = np.random.rand(10)
maximum = np.amax(random_vector)
maximum_index = np.where(random_vector == maximum)[0][0]
random_vector[maximum_index] = 0
random_vector

array([0.45960403, 0.36684572, 0.46265942, 0.70534938, 0.27591138,
       0.38312753, 0.        , 0.67621486, 0.30477757, 0.11289844])

Преобразовать массив из float в int

In [33]:
float_array = np.array([2.3, 1.3, 5.6, 3.8, 8.9])
float_array.astype(int)

array([2, 1, 5, 3, 8])

Дан массив (10,2) координат, найти расстояние от каждой точки до каждой

In [32]:
ar = np.random.rand(10, 2)
distances = []
def distance(p1, p2):
    [x1, y1] = p1
    [x2, y2] = p2
    return ((x1 - x2) ** 2 + (y1 - y2) ** 2) ** 0.5
for (i, point1) in enumerate(ar):
    tail = ar[i + 1:-1]
    for (j, point2) in enumerate(tail):
        distances.append(distance(point1, point2))

print('Distances len {0} it proof that solution is correct'.format(len(distances)))
print('Points')
print(ar)
print('------')
print(distances)


Distances len 36 it proof that solution is correct
Points
[[0.6159334  0.21029658]
 [0.397537   0.34170311]
 [0.25581836 0.16363132]
 [0.88170024 0.32402891]
 [0.76617851 0.91401382]
 [0.53410877 0.80569669]
 [0.87753237 0.92747753]
 [0.72826323 0.34829448]
 [0.03312573 0.59123688]
 [0.99264749 0.59404323]]
------
[0.25488166074247165, 0.36312599115279853, 0.28907967453017597, 0.7195773440224558, 0.6009963080897764, 0.7634019518194228, 0.177936543251034, 0.6962616478587678, 0.22758237325508776, 0.4844857253406137, 0.6807614225864406, 0.4836753982727573, 0.7573158034535314, 0.33079190867642516, 0.4416590021795518, 0.6461079743352898, 0.9074918113902114, 0.6997810338140948, 0.9848803725045583, 0.5072520506357339, 0.48211878425280474, 0.6011883806654239, 0.5939896315450299, 0.6034630137300965, 0.15534391716837273, 0.8896509373841505, 0.2561034281542518, 0.1121648513428889, 0.566988485626532, 0.8009689928536446, 0.3643766507009573, 0.49690314769930854, 0.5449559722783907, 0.598108919668501

Случайно расположить p элементов в 2D массив

In [31]:
p = [1,2,3,4,5,6,7,8,9,10,11,12]
ar = np.array(p)
ar = ar.reshape(3, 4)
np.random.shuffle(ar)
ar

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

Дан вектор [1, 2, 3, 4, 5], построить новый вектор с тремя нулями между каждым значением

In [30]:
# Вероятно здесь имелся в виду какой-то метод numpy. Но я так и не понял что здесь имелось в виду
ar = [1, 2, 3, 4, 5]
result = []
for (index, el) in enumerate(ar):
    if(index != len(ar) - 1):
        result.append(el)
        result += [0, 0, 0] 
result

[1, 0, 0, 0, 2, 0, 0, 0, 3, 0, 0, 0, 4, 0, 0, 0]

Найти наиболее частое значение в массиве

In [51]:
array = [1,1,1,1,1,2,2,2,2,1,1,1,2,9]
def find_most_frequent(arr):
    frequencies = np.bincount(arr)
    max_frequency = max(frequencies)
    return np.where(frequencies == max_frequency)[0][0]
find_most_frequent(array)

1

Найти n наибольших значений в массиве

In [54]:
array = [1,1,1,1,1,2,2,2,2,1,1,1,2,9]
def find_n_most_frequent(arr, elements_number = 1):
    frequencies = np.bincount(arr)
    result = []
    while(elements_number > 0):
        max_frequency = max(frequencies)
        if(max_frequency == 0):
            break
        else:
            most_frequent_element = np.where(frequencies == max_frequency)[0][0]
            frequencies[most_frequent_element] = 0
            result.append(most_frequent_element)
            elements_number -= 1
    return result
print(find_n_most_frequent(array, 0))
print(find_n_most_frequent(array))
print(find_n_most_frequent(array, 2))
print(find_n_most_frequent(array, 5))

[]
[1]
[1, 2]
[1, 2, 9]


## Pandas - изучение данных

Перейти по ссылке [Kaggle]( https://www.kaggle.com/openfoodfacts/world-food-facts)

Скачать датасет на свой компьютер и распаковать

Считать csv файл в датафрейм food

In [3]:
import pandas as pd
food = pd.read_csv('en.openfoodfacts.org.products.tsv', delimiter='\t')
len(food)

/home/carefreeslacker/anaconda3/lib/python3.7/site-packages/IPython/core/interactiveshell.py:2785: DtypeWarning: Columns (0,3,5,19,20,24,25,26,27,28,36,37,38,39,48) have mixed types. Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)


356027

Посмотреть первые 5 записей

In [4]:
food.head()

code                                                url  \
0   3087  http://world-en.openfoodfacts.org/product/0000...   
1   4530  http://world-en.openfoodfacts.org/product/0000...   
2   4559  http://world-en.openfoodfacts.org/product/0000...   
3  16087  http://world-en.openfoodfacts.org/product/0000...   
4  16094  http://world-en.openfoodfacts.org/product/0000...   

                      creator   created_t      created_datetime  \
0  openfoodfacts-contributors  1474103866  2016-09-17T09:17:46Z   
1             usda-ndb-import  1489069957  2017-03-09T14:32:37Z   
2             usda-ndb-import  1489069957  2017-03-09T14:32:37Z   
3             usda-ndb-import  1489055731  2017-03-09T10:35:31Z   
4             usda-ndb-import  1489055653  2017-03-09T10:34:13Z   

  last_modified_t last_modified_datetime                    product_name  \
0      1474103893   2016-09-17T09:18:13Z              Farine de blé noir   
1      1489069957   2017-03-09T14:32:37Z  Banana Chips Sweetened (Whole)   
2      1489069957   2017-03-09T14:32:37Z                         Peanuts   
3      1489055731   2017-03-09T10:35:31Z          Organic Salted Nut Mix   
4      1489055653   2017-03-09T10:34:13Z                 Organic Polenta   

  generic_name quantity         ...         fruits-vegetables-nuts_100g  \
0          NaN      1kg         ...                                 NaN   
1          NaN      NaN         ...                                 NaN   
2          NaN      NaN         ...                                 NaN   
3          NaN      NaN         ...                                 NaN   
4          NaN      NaN         ...                                 NaN   

  fruits-vegetables-nuts-estimate_100g collagen-meat-protein-ratio_100g  \
0                                  NaN                              NaN   
1                                  NaN                              NaN   
2                                  NaN                              NaN   
3                                  NaN                              NaN   
4                                  NaN                              NaN   

  cocoa_100g chlorophyl_100g carbon-footprint_100g nutrition-score-fr_100g  \
0        NaN             NaN                   NaN                     NaN   
1        NaN             NaN                   NaN                    14.0   
2        NaN             NaN                   NaN                     0.0   
3        NaN             NaN                   NaN                    12.0   
4        NaN             NaN                   NaN                     NaN   

  nutrition-score-uk_100g glycemic-index_100g water-hardness_100g  
0                     NaN                 NaN                 NaN  
1                    14.0                 NaN                 NaN  
2                     0.0                 NaN                 NaN  
3                    12.0                 NaN                 NaN  
4                     NaN                 NaN                 NaN  

[5 rows x 163 columns]

Сколько наблюдений в наборе данных?


In [7]:
print('В наборе данных {0} наблюдений'.format(len(food)))

В наборе данных 356027 наблюдений


Сколько столбцов в наборе данных?

In [12]:
print('В наборе данных {0} столбца'.format(len(food.columns)))

В наборе данных 163 столбца


Напечатайте все названия столбцов

In [13]:
columns = [column for column in food.columns]
for column in columns:
    print(column)

code
url
creator
created_t
created_datetime
last_modified_t
last_modified_datetime
product_name
generic_name
quantity
packaging
packaging_tags
brands
brands_tags
categories
categories_tags
categories_en
origins
origins_tags
manufacturing_places
manufacturing_places_tags
labels
labels_tags
labels_en
emb_codes
emb_codes_tags
first_packaging_code_geo
cities
cities_tags
purchase_places
stores
countries
countries_tags
countries_en
ingredients_text
allergens
allergens_en
traces
traces_tags
traces_en
serving_size
no_nutriments
additives_n
additives
additives_tags
additives_en
ingredients_from_palm_oil_n
ingredients_from_palm_oil
ingredients_from_palm_oil_tags
ingredients_that_may_be_from_palm_oil_n
ingredients_that_may_be_from_palm_oil
ingredients_that_may_be_from_palm_oil_tags
nutrition_grade_uk
nutrition_grade_fr
pnns_groups_1
pnns_groups_2
states
states_tags
states_en
main_category
main_category_en
image_url
image_small_url
energy_100g
energy-from-fat_100g
fat_100g
saturated-fat_100g
-buty

Какое название у 105 столбца?

In [16]:
columns[105]

'-fructose_100g'

Какой тип наблюдений в 105 столбце?

In [19]:
types = [type for type in food.dtypes]
types[105]

dtype('float64')

Как проиндексирован набор данных?

In [23]:
# Я Не совсем понял что это значит "Как проиндексирован" вероятно намёк на
food.index

RangeIndex(start=0, stop=356027, step=1)

Каково значение имени продукта в 19-м наблюдении?

In [25]:
food[19:20].get('product_name').to_string()

'19    Organic Oat Groats'

## Pandas - фильтрация данных

Считать данные по  [адресу](https://raw.githubusercontent.com/justmarkham/DAT8/master/data/chipotle.tsv). 
Присвоить переменной chipo

In [51]:
import requests
import pandas as pd

response = requests.get('https://raw.githubusercontent.com/justmarkham/DAT8/master/data/chipotle.tsv')
foods = open('chipotle.tsv', 'w')
foods.write(response.text)
foods.close()
food = pd.read_csv('chipotle.tsv', delimiter='\t')

Как много продуктов стоят более чем $10.00?

In [52]:
import re
import pandas as pd
FLOAT_REGEX = '([\d\.]+)'

def parse_price(price):
    return float(re.search(FLOAT_REGEX, price).group(1))

food['float_price'] = food['item_price'].map(lambda price: parse_price(price))
prices = food.get('float_price')
counter = 0
for float_price in prices:
    if float_price > 10:
        counter += 1
print('{0} из {1} продуктов стоят больше 10$. Что составляет {2}%'.format(counter, len(prices), float(round(counter/len(prices) * 100, 2))))

1130 из 4622 продуктов стоят больше 10$. Что составляет 24.45%


Какова цена каждого предмета? Напечатать столбцы item_name и item_price

In [45]:
food.loc[:, ['item_name', 'item_price']]

item_name item_price
0              Chips and Fresh Tomato Salsa     $2.39 
1                                      Izze     $3.39 
2                          Nantucket Nectar     $3.39 
3     Chips and Tomatillo-Green Chili Salsa     $2.39 
4                              Chicken Bowl    $16.98 
5                              Chicken Bowl    $10.98 
6                             Side of Chips     $1.69 
7                             Steak Burrito    $11.75 
8                          Steak Soft Tacos     $9.25 
9                             Steak Burrito     $9.25 
10                      Chips and Guacamole     $4.45 
11                     Chicken Crispy Tacos     $8.75 
12                       Chicken Soft Tacos     $8.75 
13                             Chicken Bowl    $11.25 
14                      Chips and Guacamole     $4.45 
15    Chips and Tomatillo-Green Chili Salsa     $2.39 
16                          Chicken Burrito     $8.49 
17                          Chicken Burrito     $8.49 
18                              Canned Soda     $2.18 
19                             Chicken Bowl     $8.75 
20                      Chips and Guacamole     $4.45 
21                         Barbacoa Burrito     $8.99 
22                         Nantucket Nectar     $3.39 
23                          Chicken Burrito    $10.98 
24                                     Izze     $3.39 
25             Chips and Fresh Tomato Salsa     $2.39 
26                             Chicken Bowl     $8.49 
27                         Carnitas Burrito     $8.99 
28                              Canned Soda     $1.09 
29                          Chicken Burrito     $8.49 
...                                     ...        ...
4592                       Barbacoa Burrito    $11.75 
4593                          Carnitas Bowl    $11.75 
4594                          Barbacoa Bowl    $11.75 
4595                           Chicken Bowl     $8.75 
4596                    Chips and Guacamole     $4.45 
4597                      Canned Soft Drink     $1.25 
4598                          Bottled Water     $1.50 
4599                           Chicken Bowl     $8.75 
4600                    Chips and Guacamole     $4.45 
4601                      Canned Soft Drink     $1.25 
4602                       Barbacoa Burrito     $9.25 
4603                       Barbacoa Burrito     $9.25 
4604                           Chicken Bowl     $8.75 
4605                    Chips and Guacamole     $4.45 
4606                      Canned Soft Drink     $1.25 
4607                          Steak Burrito    $11.75 
4608                         Veggie Burrito    $11.25 
4609                      Canned Soft Drink     $1.25 
4610                          Steak Burrito    $11.75 
4611                         Veggie Burrito    $11.25 
4612                          Carnitas Bowl     $9.25 
4613                                  Chips     $2.15 
4614                          Bottled Water     $1.50 
4615                     Chicken Soft Tacos     $8.75 
4616                    Chips and Guacamole     $4.45 
4617                          Steak Burrito    $11.75 
4618                          Steak Burrito    $11.75 
4619                     Chicken Salad Bowl    $11.25 
4620                     Chicken Salad Bowl     $8.75 
4621                     Chicken Salad Bowl     $8.75 

[4622 rows x 2 columns]

Отсортировать по имени предмета

In [46]:
food.sort_values(['item_name'])

order_id  quantity          item_name  \
3389      1360         2  6 Pack Soft Drink   
341        148         1  6 Pack Soft Drink   
1849       749         1  6 Pack Soft Drink   
1860       754         1  6 Pack Soft Drink   
2713      1076         1  6 Pack Soft Drink   
3422      1373         1  6 Pack Soft Drink   
553        230         1  6 Pack Soft Drink   
1916       774         1  6 Pack Soft Drink   
1922       776         1  6 Pack Soft Drink   
1937       784         1  6 Pack Soft Drink   
3836      1537         1  6 Pack Soft Drink   
298        129         1  6 Pack Soft Drink   
1976       798         1  6 Pack Soft Drink   
1167       481         1  6 Pack Soft Drink   
3875      1554         1  6 Pack Soft Drink   
1124       465         1  6 Pack Soft Drink   
3886      1558         1  6 Pack Soft Drink   
2108       849         1  6 Pack Soft Drink   
3010      1196         1  6 Pack Soft Drink   
4535      1803         1  6 Pack Soft Drink   
4169      1664         1  6 Pack Soft Drink   
4174      1666         1  6 Pack Soft Drink   
4527      1800         1  6 Pack Soft Drink   
4522      1798         1  6 Pack Soft Drink   
3806      1525         1  6 Pack Soft Drink   
2389       949         1  6 Pack Soft Drink   
3132      1248         1  6 Pack Soft Drink   
3141      1253         1  6 Pack Soft Drink   
639        264         1  6 Pack Soft Drink   
1026       422         1  6 Pack Soft Drink   
...        ...       ...                ...   
2996      1192         1       Veggie Salad   
3163      1263         1       Veggie Salad   
4084      1635         1       Veggie Salad   
1694       686         1       Veggie Salad   
2756      1094         1       Veggie Salad   
4201      1677         1  Veggie Salad Bowl   
1884       760         1  Veggie Salad Bowl   
455        195         1  Veggie Salad Bowl   
3223      1289         1  Veggie Salad Bowl   
2223       896         1  Veggie Salad Bowl   
2269       913         1  Veggie Salad Bowl   
4541      1805         1  Veggie Salad Bowl   
3293      1321         1  Veggie Salad Bowl   
186         83         1  Veggie Salad Bowl   
960        394         1  Veggie Salad Bowl   
1316       536         1  Veggie Salad Bowl   
2156       869         1  Veggie Salad Bowl   
4261      1700         1  Veggie Salad Bowl   
295        128         1  Veggie Salad Bowl   
4573      1818         1  Veggie Salad Bowl   
2683      1066         1  Veggie Salad Bowl   
496        207         1  Veggie Salad Bowl   
4109      1646         1  Veggie Salad Bowl   
738        304         1  Veggie Soft Tacos   
3889      1559         2  Veggie Soft Tacos   
2384       948         1  Veggie Soft Tacos   
781        322         1  Veggie Soft Tacos   
2851      1132         1  Veggie Soft Tacos   
1699       688         1  Veggie Soft Tacos   
1395       567         1  Veggie Soft Tacos   

                                     choice_description item_price  
3389                                        [Diet Coke]    $12.98   
341                                         [Diet Coke]     $6.49   
1849                                             [Coke]     $6.49   
1860                                        [Diet Coke]     $6.49   
2713                                             [Coke]     $6.49   
3422                                             [Coke]     $6.49   
553                                         [Diet Coke]     $6.49   
1916                                        [Diet Coke]     $6.49   
1922                                             [Coke]     $6.49   
1937                                        [Diet Coke]     $6.49   
3836                                             [Coke]     $6.49   
298                                            [Sprite]     $6.49   
1976                                        [Diet Coke]     $6.49   
1167                                             [Coke]     $6.49   
3875                                        [Diet Coke] 

Сколько было заказано самого дорогого предмета?

In [54]:
 food.loc[food['float_price'].idxmax()].get('quantity')

15

Сколько раз был заказан предмет "Veggie Salad Bowl"?

In [60]:
food.loc[food['item_name'] == "Veggie Salad Bowl"].get('quantity').sum()


18

Сколько раз люди заказали более чем 1 предмет "Canned Soda"?

In [70]:
len(food.loc[(food["item_name"] == "Canned Soda") & (food["quantity"] > 1)])

20