## Numpy

Импортировать NumPy под именем np

In [1]:
import numpy as np

Создать вектор (одномерный массив) размера 10, заполненный нулями

In [2]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

Создать вектор размера 10, заполненный единицами

In [45]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

Создать вектор размера 10, заполненный числом 2.5

In [44]:
np.full(10, 2.5)

array([2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5])

Создать вектор размера 10, заполненный нулями, но пятый элемент равен 1

In [43]:
ar = np.zeros(10)
ar.put(5, 1)
ar

array([0., 0., 0., 0., 0., 1., 0., 0., 0., 0.])

Развернуть вектор (первый становится последним)

In [42]:
np.flip(ar)

array([[0.59404323, 0.99264749],
       [0.59123688, 0.03312573],
       [0.34829448, 0.72826323],
       [0.92747753, 0.87753237],
       [0.80569669, 0.53410877],
       [0.91401382, 0.76617851],
       [0.32402891, 0.88170024],
       [0.16363132, 0.25581836],
       [0.34170311, 0.397537  ],
       [0.21029658, 0.6159334 ]])

Создать матрицу (двумерный массив) 3x3 со значениями от 0 до 8

In [41]:
table = np.arange(9).reshape(3, 3)
table

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

Найти индексы ненулевых элементов в [1,2,0,0,4,0]

In [40]:
test_array = np.array([1,2,0,0,4,0])
np.where(test_array != 0)[0]

array([0, 1, 4])

Создать 3x3 единичную матрицу

In [39]:
ones = np.ones([3, 3])
ones

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

Создать массив 3x3x3 со случайными значениями

In [38]:
random_array = np.random.rand(3, 3, 3)
random_array

array([[[0.67655514, 0.59622998, 0.47399939],
        [0.46822453, 0.29917652, 0.28863715],
        [0.38926314, 0.21239088, 0.42322517]],

       [[0.29104195, 0.81473485, 0.42258506],
        [0.01367719, 0.98614692, 0.314754  ],
        [0.27055911, 0.10384489, 0.74235943]],

       [[0.43469073, 0.66827687, 0.53921186],
        [0.79875573, 0.75221953, 0.41389857],
        [0.21654056, 0.42450874, 0.8939852 ]]])

Создать случайный вектор размера 30 и найти среднее значение всех элементов

In [37]:
random_vector = np.random.rand(30)
random_vector.mean()

0.6006973009886795

Перемножить матрицы 5x3 и 3x2

In [36]:
matrix1 = np.random.rand(5, 3)
matrix2 = np.random.rand(3, 2)
np.matmul(matrix1, matrix2)

array([[0.69552043, 0.2889209 ],
       [0.92415356, 0.172768  ],
       [0.7797005 , 0.0924583 ],
       [1.52742567, 0.17949509],
       [0.31142996, 0.07430366]])

Создать вектор размера 10 со значениями от 0 до 1, не включая ни то, ни другое

In [35]:
random_vector = np.random.rand(10)

Заменить максимальный элемент на ноль

In [34]:
random_vector = np.random.rand(10)
maximum = np.amax(random_vector)
maximum_index = np.where(random_vector == maximum)[0][0]
random_vector[maximum_index] = 0
random_vector

array([0.45960403, 0.36684572, 0.46265942, 0.70534938, 0.27591138,
       0.38312753, 0.        , 0.67621486, 0.30477757, 0.11289844])

Преобразовать массив из float в int

In [33]:
float_array = np.array([2.3, 1.3, 5.6, 3.8, 8.9])
float_array.astype(int)

array([2, 1, 5, 3, 8])

Дан массив (10,2) координат, найти расстояние от каждой точки до каждой

In [32]:
ar = np.random.rand(10, 2)
distances = []
def distance(p1, p2):
    [x1, y1] = p1
    [x2, y2] = p2
    return ((x1 - x2) ** 2 + (y1 - y2) ** 2) ** 0.5
for (i, point1) in enumerate(ar):
    tail = ar[i + 1:-1]
    for (j, point2) in enumerate(tail):
        distances.append(distance(point1, point2))

print('Distances len {0} it proof that solution is correct'.format(len(distances)))
print('Points')
print(ar)
print('------')
print(distances)


Distances len 36 it proof that solution is correct
Points
[[0.6159334  0.21029658]
 [0.397537   0.34170311]
 [0.25581836 0.16363132]
 [0.88170024 0.32402891]
 [0.76617851 0.91401382]
 [0.53410877 0.80569669]
 [0.87753237 0.92747753]
 [0.72826323 0.34829448]
 [0.03312573 0.59123688]
 [0.99264749 0.59404323]]
------
[0.25488166074247165, 0.36312599115279853, 0.28907967453017597, 0.7195773440224558, 0.6009963080897764, 0.7634019518194228, 0.177936543251034, 0.6962616478587678, 0.22758237325508776, 0.4844857253406137, 0.6807614225864406, 0.4836753982727573, 0.7573158034535314, 0.33079190867642516, 0.4416590021795518, 0.6461079743352898, 0.9074918113902114, 0.6997810338140948, 0.9848803725045583, 0.5072520506357339, 0.48211878425280474, 0.6011883806654239, 0.5939896315450299, 0.6034630137300965, 0.15534391716837273, 0.8896509373841505, 0.2561034281542518, 0.1121648513428889, 0.566988485626532, 0.8009689928536446, 0.3643766507009573, 0.49690314769930854, 0.5449559722783907, 0.598108919668501

Случайно расположить p элементов в 2D массив

In [31]:
p = [1,2,3,4,5,6,7,8,9,10,11,12]
ar = np.array(p)
ar = ar.reshape(3, 4)
np.random.shuffle(ar)
ar

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

Дан вектор [1, 2, 3, 4, 5], построить новый вектор с тремя нулями между каждым значением

In [30]:
# Вероятно здесь имелся в виду какой-то метод numpy. Но я так и не понял что здесь имелось в виду
ar = [1, 2, 3, 4, 5]
result = []
for (index, el) in enumerate(ar):
    if(index != len(ar) - 1):
        result.append(el)
        result += [0, 0, 0] 
result

[1, 0, 0, 0, 2, 0, 0, 0, 3, 0, 0, 0, 4, 0, 0, 0]

Найти наиболее частое значение в массиве

In [51]:
array = [1,1,1,1,1,2,2,2,2,1,1,1,2,9]
def find_most_frequent(arr):
    frequencies = np.bincount(arr)
    max_frequency = max(frequencies)
    return np.where(frequencies == max_frequency)[0][0]
find_most_frequent(array)

1

Найти n наибольших значений в массиве

In [54]:
array = [1,1,1,1,1,2,2,2,2,1,1,1,2,9]
def find_n_most_frequent(arr, elements_number = 1):
    frequencies = np.bincount(arr)
    result = []
    while(elements_number > 0):
        max_frequency = max(frequencies)
        if(max_frequency == 0):
            break
        else:
            most_frequent_element = np.where(frequencies == max_frequency)[0][0]
            frequencies[most_frequent_element] = 0
            result.append(most_frequent_element)
            elements_number -= 1
    return result
print(find_n_most_frequent(array, 0))
print(find_n_most_frequent(array))
print(find_n_most_frequent(array, 2))
print(find_n_most_frequent(array, 5))

[]
[1]
[1, 2]
[1, 2, 9]


## Pandas - изучение данных

Перейти по ссылке [Kaggle]( https://www.kaggle.com/openfoodfacts/world-food-facts)

Скачать датасет на свой компьютер и распаковать

Считать csv файл в датафрейм food

Посмотреть первые 5 записей

Сколько наблюдений в наборе данных?


Сколько столбцов в наборе данных?

Напечатайте все названия столбцов

Какое название у 105 столбца?

Какой тип наблюдений в 105 столбце?

Как проиндексирован набор данных?

Каково значение имени продукта в 19-м наблюдении?

## Pandas - фильтрация данных

Считать данные по  [адресу](https://raw.githubusercontent.com/justmarkham/DAT8/master/data/chipotle.tsv). 
Присвоить переменной chipo

Как много продуктов стоят более чем $10.00?

Какова цена каждого предмета? Напечатать столбцы item_name и item_price

Отсортировать по имени предмета

Сколько было заказано самого дорогого предмета?

Сколько раз был заказан предмет "Veggie Salad Bowl"?

Сколько раз люди заказали более чем 1 предмет "Canned Soda"?